import './globals.css';
import localFont from "next/font/local";

const clashGrotesk = localFont({
  src: "../fonts/ClashGrotesk-Variable.woff2", // path is from /public
  variable: "--font-clash",
  weight: "100 700", // variable range
  display: "swap",
});


export const metadata = {
  title: 'My Blog',
  description: 'Generated by Next.js',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={clashGrotesk.variable}>
      <body>
        {children}
      </body>
    </html>
  );
}